### ISSUE TITLE
Allow mutliple headers with the same key

### ISSUE THREAD

**Issue by lancejjohnson** [beam-community/bamboo#469]
See #360 and #343 for examples and use cases.

**Comment by alexparker** [comment]
Any initial thoughts on this and possible approach? I'd love to help out with a pull request if you have some initial ideas to explore or suggestions.

**Comment by lancejjohnson** [comment]
@alexparker I started work on this as I had some time available. I've opened a WIP PR that you're welcome to take a look at, review, improve, etc. I've not touched any of the adapters with this change so figuring out how/when to do that is still necessary. I've tried to maintain backwards compatibility by adding behavior and making the current behavior the default option. Please feel free to take what I've put it up and run with it.

https://github.com/thoughtbot/bamboo/pull/472

**Comment by alexparker** [comment]
Aweome @lancejjohnson I started fiddling around with this yesterday, getting to know the code base https://github.com/thoughtbot/bamboo/compare/469-multiple-headers...alexparker:469-multiple-headers#diff-2a2f52b732e92f5dcc62d5bd29253ef0R228

Interesting to note if you _do_ get a list into the headers value, the `to_string(value)` ends up just concatenating the list (no commas) 
But I'm wondering if the `normalize_headers` method might be per adapter based
Otherwise most places the headers property is expected to be a map.

Anyways, just jotting thoughts/notes. I'll try to find some more time today / tomorrow to get a little further to a more tangible place
