### ISSUE TITLE
Add attachment `content-disposition` and `content-id` fields

### ISSUE THREAD

**Issue by egeersoz** [beam-community/bamboo#502]
SendGrid api has the following properties for emails:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

See the `disposition` and `content_id` properties under attachments.

These turn out to be pretty important when you're sending .ics files (calendar invites). By default SendGrid populates the disposition value with "attachment" if it isempty, but Microsoft Outlook requires it to be set to "inline" in order to display the .ics file as a "native" invitation.

I think since there's a content_type field in the `%Bamboo.Attachment{}` struct already, it makes sense to also be able to set a `content_disposition` field.

(Note that when setting disposition to "inline", Sendgrid also requires a unique `content_id` to be set.)

**Comment by germsvel** [comment]
Hi @egeersoz, thanks for opening this issue and for the patience! I'm taking over maintenance of Bamboo and trying to go through all the issues. 

Having the ability to set `content_disposition` to `%Bamboo.Attachment{}` makes sense to me and then mapping that to the `disposition` attribute in the `SendgridAdapter`. 

If this is still of interest to you, I'd be happy to review a PR. Otherwise, I'll try to get to this when I have some time.

**Comment by demos74dx** [comment]
Any chance we can merge @sreecodeslayer PR? It looks good to me.

**Comment by sb8244** [comment]
Ran into a problem that I think this issue would solve.

When using the SendgridAdapter, it's not possible (maybe incorrect?) to refer to the inlined images using `cid:`. This is because the Content-Id header is not set on attachments for SendgridAdapter.

Is there an alternative?
