### ISSUE TITLE
Allow `iodata()` usage

### ISSUE THREAD

**Issue by fuelen** [beam-community/bamboo#610]
HTML and text bodies can be rendered as iodata. The idea is to encode iodata to string on an adapter level, or use iodata as is if possible. This approach in theory would improve performance for some adapters.

**Comment by germsvel** [comment]
Hi @fuelen thank you for opening this issue. 

I understand that in theory allowing iodata would improve performance. But I'm wondering, are you experiencing performance issues with Bamboo right now? 

If so, I'd love to get a better sense of where the bottleneck lies. If it turns out allowing for iodata usage fixes that bottleneck, then it might make sense to do this work. Otherwise, I don't know if this is worth pursuing right now.

**Comment by fuelen** [comment]
Hi @germsvel 

No, I don't have performance issues for now. I've worked on custom templating engine and realized, that I've to convert iodata to string manually, because bamboo doesn't support iodata. I'd say it is more about design approaches overall.

**Comment by germsvel** [comment]
>  I've worked on custom templating engine and realized, that I've to convert iodata to string manually, because bamboo doesn't support iodata. 

Ohhh, got it. Thanks for adding that clarity @fuelen. I don't have a good sense (off the top of my head) of how we would support that. But if there's a straightforward way, I'd be happy to review a PR for that.
